### ISSUE TITLE
Which tool do you use to generate your personal blog?

### ISSUE THREAD

**Issue by dclong** [vuquangtrong/vuquangtrong.github.io#2]
May I ask which static site generator do you use to generate you personal blog? And which theme do you use?

**Comment by vuquangtrong** [comment]
It's MkDocs using Material Themes. Please refer to the <https://squidfunk.github.io/mkdocs-material>.

**Comment by dclong** [comment]
Does MkDocs support Jupyter notebooks?

**Comment by dclong** [comment]
Found this https://github.com/danielfrg/mkdocs-jupyter. 

Thank you so much for the info!
